import { APPOINTMENT_STATUS } from '../interfaces/appointment-status';

export const ALLOWED_STATUS_TRANSITIONS: Record<APPOINTMENT_STATUS, APPOINTMENT_STATUS[]> = {
	[APPOINTMENT_STATUS.PENDING]: [APPOINTMENT_STATUS.CONFIRMED, APPOINTMENT_STATUS.CANCELED],
	[APPOINTMENT_STATUS.CONFIRMED]: [APPOINTMENT_STATUS.COMPLETED, APPOINTMENT_STATUS.CANCELED, APPOINTMENT_STATUS.NO_SHOW],
	[APPOINTMENT_STATUS.COMPLETED]: [],
	[APPOINTMENT_STATUS.CANCELED]: [],
	[APPOINTMENT_STATUS.NO_SHOW]: [],
	[APPOINTMENT_STATUS.RESCHEDULED]: [],
	[APPOINTMENT_STATUS.TRANSFERRED]: [],
};
