allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: true
  sharp: true
  unrs-resolver: true

ignoredOptionalDependencies:
  - preview-email

overrides:
  js-yaml@3: 3.15.1
  js-yaml@5: 5.2.2
  linkify-it: 5.0.2
  nodemailer: 9.0.5