export enum APPOINTMENT_STATUS {
	PENDING = 'PENDING',
	CONFIRMED = 'CONFIRMED',
	COMPLETED = 'COMPLETED',
	CANCELED = 'CANCELED',
	NO_SHOW = 'NO_SHOW',
	RESCHEDULED = 'RESCHEDULED',
	TRANSFERRED = 'TRANSFERRED',
}

